# Generated by Django 3.1.1 on 2020-09-13 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crust', '0004_auto_20200912_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='coords',
        ),
    ]
